
#EmAnt Standard Makefile

LD= g++
CFLAGS= -Wall -O3
CXXFLAGS= $(CFLAGS) -std=c++11
LDFLAGS= -lm -lGL -lGLU -lglut

OBJS= 	main.o\
		rbody.o
		
EXEC=	poinsot

	
all: $(OBJS)
	$(LD) -o $(EXEC) $(OBJS) $(LDFLAGS)
	
clean:
	-@rm -f $(EXEC) *~ *.o *.a

exec: all
	./$(EXEC)
	
#DEPS (Generated by g++ -MM )

main.o: main.cpp rbody.h defs.h
rbody.o: rbody.cpp rbody.h defs.h




